// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core'

/** Commands */
export const commands = {
  getStatus: () => typedError<DockerStatus, string>(__TAURI_INVOKE('get_status')),
  getContainers: () => typedError<DockerContainerResult, string>(__TAURI_INVOKE('get_containers')),
  runContainerCommand: (command: DockerContainerCommand, id: string) =>
    typedError<null, string>(__TAURI_INVOKE('run_container_command', { command, id })),
}

/* Types */
// Docker client version info.
export type DockerClientVersion = {
  name: string
  version: string
  apiVersion: string
  os: string
  arch: string
  context: string
}

export type DockerComposeProject = {
  project: string
  state: DockerContainerState
}

export type DockerContainer = {
  id: string
  name: string
  image: string
  state: DockerContainerState
  // Raw state — only populated if the `state` could not be determined.
  stateRaw: string | null
  status: string
  statusDetail: string | null
  labels: { [key in string]: string | null }
  ports: DockerNetworkBinding[]
  platform: DockerContainerPlatform
  // Docker Compose info, if available.
  compose: DockerContainerComposeInfo | null
}

export type DockerContainerCommand = 'unknown' | 'start' | 'stop' | 'restart' | 'pause' | 'remove'

export type DockerContainerComposeInfo = {
  // Docker Compose project name.
  project: string
  // Service name within the project.
  service: string
}

export type DockerContainerPlatform = {
  architecture: string
  os: string
  variant: string | null
}

// Docker container list result — contains both, individual containers and Docker Compose projects.
export type DockerContainerResult = {
  containers: DockerContainer[]
  projects: DockerComposeProject[]
}

// Docker container state — including a partial state for groups/projects.
export type DockerContainerState =
  | 'unknown'
  | 'created'
  | 'running'
  | 'paused'
  | 'restarting'
  | 'removing'
  | 'exited'
  | 'dead'
  // Docker Compose state only — indicates that some containers in the project are running, but not all.
  | 'partial'

export type DockerNetworkBinding = {
  hostPort: number | null
  containerPort: number
  protocol: string
}

// Docker server/engine version info.
export type DockerServerVersion = {
  name: string
  version: string
  apiVersion: string
  os: string
  arch: string
}

// Docker status — containing both, client and server versions.
export type DockerStatus = {
  client: DockerClientVersion
  // This can be unavailable if the Docker daemon is unavailable.
  server: DockerServerVersion | null
}

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result }
  } catch (e) {
    if (e instanceof Error) throw e
    return { status: 'error', error: e as any }
  }
}
